//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eneco.Invest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxaptaIsabel
    {
        public int AxaptaId { get; set; }
        public int IsabelId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Axapta Axapta { get; set; }
        public virtual Isabel Isabel { get; set; }
    }
}
